[package]
name = "vulkan-tutorial"
version = "0.1.0"
authors = ["Neightro"]
edition = "2018"

[dependencies]
vulkano = "0.19.0"
vulkano-win = "0.19.0"
vulkano-shaders = "0.19.0"
winit = "0.22.1"
cgmath = "0.17.0"
image = "0.23.4"
tobj = "2.0.2"
